#!/usr/bin/env node

import { Command } from 'commander';
import inquirer from 'inquirer';
import fs from 'fs-extra';
import chalk from 'chalk';
import path from 'path';
import { fileURLToPath } from 'url';
import { exec } from 'child_process';
import util from 'util';
import ora from 'ora';
import crypto from 'crypto';

const execPromise = util.promisify(exec);
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Inquirer Fix for ESM
const prompt = inquirer.prompt ?? inquirer.default?.prompt ?? inquirer.default;

const DEPENDENCIES = {
  firebase: "firebase",
  betterauth: "better-auth", 
  jwt: "jsonwebtoken bcryptjs cookie",
};

function getPackageManager() {
  const userDir = process.cwd();
  if (fs.existsSync(path.join(userDir, 'yarn.lock'))) return 'yarn add';
  if (fs.existsSync(path.join(userDir, 'pnpm-lock.yaml'))) return 'pnpm add';
  if (fs.existsSync(path.join(userDir, 'bun.lockb'))) return 'bun add';
  return 'npm install';
}

// 🔥 ENV টেমপ্লেট জেনারেটর
function getEnvTemplate(provider) {
  if (provider === 'betterauth') {
    const secret = crypto.randomBytes(32).toString('hex');
    return `
# Better Auth Configuration (Generated by jr-auth)
BETTER_AUTH_SECRET="${secret}"
BETTER_AUTH_URL="http://localhost:3000"
# Add your database connection string below
DATABASE_URL=""
# Social Providers (Optional)
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""
`;
  } 
  
  if (provider === 'firebase') {
    return `
# Firebase Configuration
NEXT_PUBLIC_FIREBASE_API_KEY=""
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=""
NEXT_PUBLIC_FIREBASE_PROJECT_ID=""
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=""
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=""
NEXT_PUBLIC_FIREBASE_APP_ID=""
`;
  }

  return '';
}

const program = new Command();

program
  .name('jr-auth')
  .description('Production Ready Auth CLI')
  .version('1.0.0');

program
  .command('add')
  .description('Add an authentication provider')
  .action(async () => {
    
    try {
      const answers = await prompt([
        {
          type: 'list',
          name: 'provider',
          message: 'Which auth setup do you need?',
          choices: ['Firebase', 'Better Auth', 'JWT'], 
        },
      ]);

      const providerName = answers.provider.toLowerCase().replace(/\s/g, '');
      const templatePath = path.join(__dirname, 'templates', providerName);
      
      const spinner = ora('Checking requirements...').start();

      if (!fs.existsSync(templatePath)) {
        spinner.fail(chalk.red(`Template not found!`));
        return;
      }

      // ১. ফাইল কপি করা
      spinner.text = 'Generating boilerplate...';

      if (providerName === 'betterauth') {
        // Auth Config -> lib/auth.ts
        const libPath = path.join(process.cwd(), 'lib');
        await fs.ensureDir(libPath);
        await fs.copy(path.join(templatePath, 'auth.ts'), path.join(libPath, 'auth.ts'));

        // API Route -> app/api/auth/[...all]/route.ts
        const apiPath = path.join(process.cwd(), 'app', 'api', 'auth', '[...all]');
        await fs.ensureDir(apiPath); 
        await fs.copy(path.join(templatePath, 'route.ts'), path.join(apiPath, 'route.ts'));

        // Client Helper -> lib/auth-client.ts
        await fs.copy(
            path.join(templatePath, 'auth-client.ts'), 
            path.join(libPath, 'auth-client.ts')
        );

        // Success Message (Updated)
        spinner.succeed(chalk.green(`Generated: lib/auth.ts, lib/auth-client.ts, api routes`));

      } else {
        // Firebase / JWT
        const targetPath = path.join(process.cwd(), 'lib', 'auth', providerName);
        await fs.copy(templatePath, targetPath);
        
        spinner.succeed(chalk.green(`Files generated successfully.`));
      }

      // ২. .env ফাইল সেটআপ
      const envData = getEnvTemplate(providerName);
      if (envData) {
        const envPath = path.join(process.cwd(), '.env.local');
        try {
            if (fs.existsSync(envPath)) {
                await fs.appendFile(envPath, envData);
                console.log(chalk.blue(`ℹ️  Added env variables to existing .env.local`));
            } else {
                await fs.writeFile(envPath, envData);
                console.log(chalk.blue(`ℹ️  Created .env.local file`));
            }
        } catch (e) {
            console.log(chalk.yellow('⚠️  Could not create .env file (Permission issue?)'));
        }
      }

      // ৩. ডিপেন্ডেন্সি ইনস্টল
      const packagesToInstall = DEPENDENCIES[providerName];
      if (packagesToInstall) {
        const installCmd = getPackageManager();
        const installSpinner = ora(`${chalk.yellow('Installing dependencies:')} ${packagesToInstall}...`).start();
        
        // 🔥 FIX: React 19 / Next.js 15 Conflict Solver
        // কমান্ড তৈরি করা
        let finalCommand = `${installCmd} ${packagesToInstall}`;

        // যদি npm হয়, তাহলে --legacy-peer-deps যোগ করো
        if (installCmd.includes('npm')) {
            finalCommand += ' --legacy-peer-deps';
        }

        try {
            await execPromise(finalCommand);
            installSpinner.succeed(chalk.green('Dependencies installed!'));
        } catch (installError) {
            // যদি এরপরও ফেইল করে, ম্যানুয়ালি ইনস্টল করতে বলা
            installSpinner.fail(chalk.red('Auto-install failed.'));
            console.log(chalk.yellow(`\n⚠️  Please run this command manually:\n   ${finalCommand}`));
        }
      }

      console.log('');
      console.log(chalk.bold.cyan('🎉  Setup Complete!'));
      console.log(chalk.yellow('👉 Action Required: Open .env.local and fill in your API keys.'));

    } catch (err) {
      console.error(chalk.red('\n❌ Error:'), err);
    }
  });

program.parse(process.argv);